FROM ubuntu:14.04
MAINTAINER yussandeveloper@gmail.com

RUN sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0x5a16e7281be7a449
RUN add-apt-repository ppa:nginx/stable
RUN sudo add-apt-repository "deb http://dl.hhvm.com/ubuntu $(lsb_release -sc) main"
RUN apt-get update -y 
RUN apt-get install -y software-properties-common
RUN apt-get install -y --allow-unauthenticated supervisor curl hhvm nginx git
RUN mkdir /app
RUN apt-get autoremove -y
RUN apt-get clean -y

COPY app /app
COPY etc /etc

CMD ["/etc/supervisor/supervisor.sh"]

EXPOSE 80
EXPOSE 443